name: tests

on: [push, pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  unit-tests:
    runs-on: [ ubuntu-latest ]
    strategy:
      fail-fast: false
      matrix:
        node: [ "lts/-1", "lts/-2", "lts/*" ]
        package:
          - name: sparqlc
            path: packages/sparqlc
          - name: esbuild-plugin-sparql
            path: packages/esbuild-plugin-sparql
          - name: node-loader-sparql
            path: packages/node-loader-sparql
          - name: vite-plugin-sparql
            path: packages/vite-plugin-sparql
    steps:
      - uses: actions/checkout@v6
      - uses: fabasoad/setup-prolog-action@v1
      - uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node }}
      - run: npm ci
      - run: npm run -w sparqlc build
      - run: npx c8 --all --src ${{ matrix.package.path }} --include ${{ matrix.package.path }} --reporter lcovonly --reporter text npm run -w ${{ matrix.package.name }} test
      - name: Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: ${{ matrix.package.name }}

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: fabasoad/setup-prolog-action@v1
      - uses: actions/setup-node@v6
        with:
          node-version: lts/*
      - run: npm ci
      - run: npm run lint

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: fabasoad/setup-prolog-action@v1
      - uses: actions/setup-node@v6
        with:
          node-version: lts/*
      - run: npm ci
      - run: npm run -ws --if-present build
